[2020-06-24 09:29:56,651] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,651] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,652] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,652] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,652] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,653] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:29:56,653] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:30:14,209] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 09:30:14,209] [threaten.py:1490] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 11:06:07,270] [monit.py:2832] [monit:seardat] [ERROR]- 请求出错：Compinfo matching query does not exist.
[2020-06-24 15:26:26,486] [safety.py:1335] [safety:seardat] [ERROR]- 请求出错：Compinfo matching query does not exist.
[2020-06-24 15:29:22,743] [safety.py:1335] [safety:seardat] [ERROR]- 请求出错：Compinfo matching query does not exist.
[2020-06-24 15:29:32,704] [safety.py:442] [safety:sear_info] [ERROR]- 获取地图数据出错：ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='119.90.98.16', port=9200): Read timed out. (read timeout=10))
[2020-06-24 15:32:04,567] [safety.py:1335] [safety:seardat] [ERROR]- 请求出错：Compinfo matching query does not exist.
[2020-06-24 15:32:14,564] [safety.py:442] [safety:sear_info] [ERROR]- 获取地图数据出错：ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='119.90.98.16', port=9200): Read timed out. (read timeout=10))
[2020-06-24 15:32:45,700] [safety.py:1335] [safety:seardat] [ERROR]- 请求出错：Compinfo matching query does not exist.
[2020-06-24 15:32:55,650] [safety.py:442] [safety:sear_info] [ERROR]- 获取地图数据出错：ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='119.90.98.16', port=9200): Read timed out. (read timeout=10))
[2020-06-24 15:35:36,655] [safety.py:1336] [safety:seardat] [ERROR]- 请求出错：Compinfo matching query does not exist.
[2020-06-24 15:37:16,891] [safety.py:1335] [safety:seardat] [ERROR]- 请求出错：Compinfo matching query does not exist.
[2020-06-24 15:37:26,883] [safety.py:442] [safety:sear_info] [ERROR]- 获取地图数据出错：ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='119.90.98.16', port=9200): Read timed out. (read timeout=10))
[2020-06-24 17:30:58,832] [threaten.py:254] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,832] [threaten.py:254] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,833] [threaten.py:254] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,833] [threaten.py:254] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,833] [threaten.py:254] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,834] [threaten.py:254] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,836] [threaten.py:254] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,836] [threaten.py:254] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,924] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,924] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,925] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,926] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,926] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,926] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,927] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:30:58,927] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:31:15,222] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:31:15,222] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:31:15,222] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:31:15,223] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:31:15,223] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
[2020-06-24 17:31:15,223] [threaten.py:1477] [threaten:sear_info] [ERROR]- 解析威胁情报详细数据报错：'geo'
